pool:
  name: Arm64
  vmImage: 'ubuntu-22.04'

trigger:
- main
resources:
- repo: self
variables:
  imagePullSecret: 'regcred'
stages:
- stage: Deploy
  displayName: Deploy Konga
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    
    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        namespace: kong
        action: createSecret
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: 'DockerConnection'
      continueOnError: true
    
    - task: replacetokens@3
      displayName: Replace tokens in k8s files
      inputs:
        rootDirectory: '$(Build.SourcesDirectory)/konga-k8s'
        targetFiles: '**/*.yaml'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '__'
        tokenSuffix: '__'
    
    - task: KubernetesManifest@0
      displayName: Deploy Konga to Kubernetes
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        namespace: kong
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/konga-k8s/secrets.yaml
          $(Build.SourcesDirectory)/konga-k8s/configmap.yaml
          $(Build.SourcesDirectory)/konga-k8s/deployment.yaml
          $(Build.SourcesDirectory)/konga-k8s/services.yaml
          $(Build.SourcesDirectory)/konga-k8s/certificate.yaml
          $(Build.SourcesDirectory)/konga-k8s/ingress.yaml
        imagePullSecrets: |
          $(imagePullSecret)
        containers: 'manoelvsneto/konga:$(Build.BuildId)'