pool:
  name: Arm64
  vmImage: 'ubuntu-22.04'

trigger:
- main
resources:
- repo: self
variables:
  imagePullSecret: 'regcred'
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerConnection'
        repository: 'manoelvsneto/konga'
        command: 'buildAndPush'
        tags: '$(Build.BuildId)'
        Dockerfile: '$(Build.SourcesDirectory)/konga/Dockerfile'
    
    - task: KubernetesManifest@0
      displayName: Create imagePullSecret
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        action: createSecret
        secretName: $(imagePullSecret)
        dockerRegistryEndpoint: 'DockerConnection'
    
    - task: PublishPipelineArtifact@1
      displayName: Publish Report
      inputs:
        artifact: '_backend'
        publishLocation: 'pipeline'
    
    - task: KubernetesManifest@0
      displayName: Deploy to Kubernetes cluster
      inputs:
        kubernetesServiceConnection: K8SOracleCloud
        namespace: kong
        action: deploy
        manifests: |
          $(Build.SourcesDirectory)/konga-k8s/secrets.yaml
          $(Build.SourcesDirectory)/konga-k8s/configmap.yaml
          $(Build.SourcesDirectory)/konga-k8s/deployment.yaml
          $(Build.SourcesDirectory)/konga-k8s/services.yaml
          $(Build.SourcesDirectory)/konga-k8s/certificate.yaml
          $(Build.SourcesDirectory)/konga-k8s/ingress.yaml
        imagePullSecrets: |
          $(imagePullSecret)
        containers: 'manoelvsneto/konga:$(Build.BuildId)'