apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-admin-api-ingress
  namespace: kong
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - kong.archse.eng.br
    secretName: framework-tls
  rules:
  - host: kong.archse.eng.br
    http:
      paths:
      - path: /kong-admin
        pathType: Prefix
        backend:
          service:
            name: kong-service
            port:
              number: 8001
