apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: framework-tls
  namespace: kong
spec:
  secretName: framework-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - kong.archse.eng.br