apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: framework-ingress
  namespace: kong
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/strip-path: "true"
    konghq.com/preserve-host: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - kong.archse.eng.br
    secretName: framework-tls
  rules:
  - host: kong.archse.eng.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kong-service
            port:
              number: 80