apiVersion: apps/v1
kind: Deployment
metadata:
  name: kongadmin
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kongadmin
  template:
    metadata:
      labels:
        app: kongadmin
    spec:
      containers:
      - name: kongadmin
        image: pocketdigi/kong-admin-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: KONG_ADMIN_URL
          value: "http://kong-service:8001"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kongadmin-service
  namespace: kong
spec:
  selector:
    app: kongadmin
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kongadmin-ingress
  namespace: kong
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: kong
  tls:
  - hosts:
    - kong.archse.eng.br
    secretName: framework-tls
  rules:
  - host: kong.archse.eng.br
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: kongadmin-service
            port:
              number: 8080
