apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
  namespace: kong
type: Opaque
stringData:
  KONG_ADMIN_TOKEN: __KONG_ADMIN_TOKEN__
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "postgres-service.default.svc.cluster.local"
  KONG_PG_PORT: "5432"
  KONG_PG_USER: "kong"
  KONG_PG_PASSWORD: "Kong@Postgres2024"
  KONG_PG_DATABASE: "kong"
