apiVersion: v1
kind: Secret
metadata:
  name: kong-secrets
  namespace: kong
type: Opaque
stringData:
  KONG_ADMIN_TOKEN: "__KONG_ADMIN_TOKEN__"
  KONG_DATABASE: "postgres"
  KONG_PG_HOST: "__KONG_PG_HOST__"
  KONG_PG_PORT: "5432"
  KONG_PG_USER: "__KONG_PG_USER__"
  KONG_PG_PASSWORD: "__KONG_PG_PASSWORD__"
  KONG_PG_DATABASE: "__KONG_PG_DATABASE__"
