apiVersion: v1
kind: Service
metadata:
  name: konga-postgres-service
  namespace: kong
spec:
  selector:
    app: konga-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: konga-service
  namespace: kong
spec:
  selector:
    app: konga
  ports:
  - name: http
    port: 1337
    targetPort: 1337
    protocol: TCP
  type: ClusterIP
